### PR TITLE
Test for Mongoid HEAD version (v6).

### PR DESCRIPTION
**Pull request by phyllisstein**
Adds a check to `Mongoid::Compatibility::Version` that detects Mongoid 6 and updates the relevant test, in support of a fix for digitalplaywright/mongoid-slug#216.

### CODE REVIEW

**Comment by dblock** [comment]
It looks like it's passing minus rbx, which is a known issue.

Change `rbx-*` in .travis.yml to `rbx-2` and add it to allow-failures.

**Comment by phyllisstein** [comment]
Looks like tests for Mongoid 6 are doomed to fail on Ruby versions under 2.2.2, as it requires ActiveSupport 5.0.0.rc1. Not totally sure how to handle this in the Travis settings---any suggestions?

**Comment by dblock** [comment]
You want to re-create a matrix like [this one](https://github.com/dblock/slack-ruby-client/blob/master/.travis.yml).

**Comment by phyllisstein** [comment]
Thanks so much! Hadn't seen that syntax before and couldn't find good docs for it. Tests appear to be passing now with Mongoid 6! 🎉

**Comment by dblock** [comment]
Merged squashed. Thanks. 

Do you want to do a release of mongoid-compatibility? I'd be happy to add you to contributors and rubygems, can always use some help!

**Comment by phyllisstein** [comment]
Sure thing! Happy to lend a hand. Let me know if there's anything special you'd like me to do.

**Pull request merged**
